name: Build TensorRT-LLM

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    paths:
      - "backends/**"
      - "server/**"
      - "proto/**"
      - "router/**"
      - "launcher/**"
      - "Cargo.lock"
      - "rust-toolchain.toml"
    branches:
      - "main"

jobs:
  checkout:
    runs-on:
      group: aws-highmemory-32-plus-priv
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

  call-setup-aws-s3-cache:
    needs: checkout
    uses: ./.github/workflows/s3-cache.yaml@s3-cache  # TODO: Change @s3-cache to @main when merged
    with:
      runner-group: "aws-highmemory-32-plus-priv"
    secrets: inherit

  build:
    runs-on:
      group: aws-highmemory-32-plus-priv
    needs: call-setup-aws-s3-cache
    steps:
      - name: "Setup sccache"
        run: apt update && apt upgrade -y




